import test from 'node:test';import assert from 'node:assert/strict';import LZString from 'lz-string';
import {Assets,ASSET_ROOT,RECYCLE_ROOT,GRACE_MS,parseDrawing,sha256} from '../src/assets.js';
function fixture(){
 const map=new Map();let open=0,creates=0,saves=0;const plugin={data:{},busy:new Set(),app:{workspace:{getLeavesOfType:()=>Array.from({length:open},()=>({}))},metadataCache:{resolvedLinks:{}}},persist:async()=>{saves++;}};
 const put=(path,text='')=>{const f={path,name:path.split('/').pop(),extension:path.split('.').pop(),text,stat:{size:text.length,ctime:Date.now()}};map.set(path,f);return f;};
 const vault=plugin.app.vault={getFiles:()=>[...map.values()].filter(f=>f.stat),getAbstractFileByPath:path=>map.get(path),read:async f=>f.text,createFolder:async path=>{map.set(path,{path});manager.revision++;},create:async(path,text)=>{assert.equal(map.has(path),false);creates++;manager.revision++;return put(path,text);},rename:async(file,to)=>{assert.equal(map.has(to),false);map.delete(file.path);file.path=to;map.set(to,file);manager.revision++;},trash:async file=>{map.delete(file.path);manager.revision++;}};
 const manager=new Assets(plugin);return {manager,plugin,put,map,vault,open:n=>open=n,counts:()=>({creates,saves})};
}
const svg='<svg xmlns="http://www.w3.org/2000/svg"><text>科技树</text></svg>';
test('identical cards across drawings reuse one immutable file, including concurrent requests',async()=>{const f=fixture();const [a,b]=await Promise.all([f.manager.acquire(svg),f.manager.acquire(svg)]);assert.equal(a,b);assert.equal(f.counts().creates,1);assert.equal(Object.keys(f.manager.records).length,1);await f.manager.acquire(svg);assert.equal(f.counts().creates,1);assert.equal(f.manager.active,0);});
test('changed content gets a separate asset and never mutates the old SVG',async()=>{const f=fixture(),a=await f.manager.acquire(svg),text=a.text,b=await f.manager.acquire(svg.replace('科技树','新标题'));assert.notEqual(a.path,b.path);assert.equal(a.text,text);});
test('compressed scenes parse and malformed scenes fail closed',()=>{const scene={elements:[{id:'card'}]},text='```compressed-json\n'+LZString.compressToBase64(JSON.stringify(scene))+'\n```';assert.deepEqual(parseDrawing(text),scene);assert.throws(()=>parseDrawing('```compressed-json\ninvalid\n```'));});
test('cross-drawing embedded links and encoded Markdown links both protect assets',async()=>{const f=fixture(),a=await f.manager.acquire(svg);f.put('A.excalidraw.md','## Embedded Files\nabc: [['+a.path+']]\n```json\n{"elements":[]}\n```');assert.equal((await f.manager.scan()).rows[0].status,'referenced');f.map.delete('A.excalidraw.md');f.put('note.md','![]('+encodeURIComponent(a.path)+')');assert.equal((await f.manager.scan()).rows[0].status,'referenced');});
test('no cleanup during undo-capable open drawings, and seven days start at first observation',async()=>{const f=fixture(),a=await f.manager.acquire(svg);await f.manager.observe();assert.equal((await f.manager.scan()).rows[0].eligible,false);await assert.rejects(f.manager.recycle([a.path]),/7 天/);f.manager.records[a.path].unreferencedSince=Date.now()-GRACE_MS-1;f.open(1);await assert.rejects(f.manager.recycle([a.path]),/撤销历史/);assert.equal(f.map.has(a.path),true);});
test('unreferenced assets can be quarantined and restored to their original path',async()=>{const f=fixture(),a=await f.manager.acquire(svg),path=a.path;f.manager.records[path].unreferencedSince=Date.now()-GRACE_MS-1;await f.manager.recycle([path]);assert.equal(f.map.has(path),false);assert.equal((await f.manager.scan()).rows[0].status,'recycled');await f.manager.restore(path);assert.equal(f.map.has(path),true);assert.equal(f.manager.records[path].quarantinePath,undefined);});
test('reusing a recycled image restores it rather than duplicating the asset',async()=>{const f=fixture(),a=await f.manager.acquire(svg),path=a.path;f.manager.records[path].unreferencedSince=Date.now()-GRACE_MS-1;await f.manager.recycle([path]);const b=await f.manager.acquire(svg);assert.equal(b.path,path);assert.equal(f.counts().creates,1);assert.equal(f.manager.records[path].quarantinePath,undefined);});
test('last-minute references, edits, parse failures, and forged records prevent recycling',async()=>{for(const mode of ['reference','edit','parse','forged']){const f=fixture(),a=await f.manager.acquire(svg),path=a.path;f.manager.records[path].unreferencedSince=Date.now()-GRACE_MS-1;if(mode==='reference')f.put('note.md','[['+path+']]');if(mode==='edit')a.text+='changed';if(mode==='parse')f.put('bad.excalidraw.md','broken');if(mode==='forged')f.manager.records['notes/do-not-delete.svg']={hash:'fake',unreferencedSince:1};await assert.rejects(f.manager.recycle([path]));assert.equal(f.map.has(path),true);}});
test('vault change during journal persistence aborts before file movement',async()=>{const f=fixture(),a=await f.manager.acquire(svg),path=a.path;f.manager.records[path].unreferencedSince=Date.now()-GRACE_MS-1;f.plugin.persist=async()=>{f.put('new.md','[['+path+']]');f.manager.revision++;};await assert.rejects(f.manager.recycle([path]),/仓库已改变/);assert.equal(f.map.has(path),true);});
test('failed publication leaves journaled assets discoverable, never deletes shared files',async()=>{const f=fixture();f.plugin.persist=async()=>{throw Error('disk full');};await assert.rejects(f.manager.acquire(svg),/disk full/);assert.equal(f.manager.active,0);assert.equal(f.manager.pending.size,0);assert.equal(Object.keys(f.manager.records).length,1);});
test('restart recovers a file created before journal persistence',async()=>{const f=fixture(),a=await f.manager.acquire(svg),path=a.path;f.plugin.data.resources={};await f.manager.observe();assert.equal(f.manager.records[path].hash,await sha256(a.text));assert.equal((await f.manager.scan()).rows[0].eligible,false);});
test('legacy Pasted Image files are reported but never adopted or recycled',async()=>{const f=fixture();f.put('Attachments/Pasted Image test.svg',svg);const r=await f.manager.observe();assert.equal(r.legacy.length,1);assert.equal(r.rows.length,0);await assert.rejects(f.manager.recycle([r.legacy[0].path]));});
test('unsaved Markdown editor links protect resources before a disk save',async()=>{const f=fixture(),a=await f.manager.acquire(svg);f.plugin.app.workspace.iterateAllLeaves=fn=>fn({view:{editor:{getValue:()=>`![[${a.path}]]`}}});assert.equal((await f.manager.scan()).rows[0].status,'referenced');});
test('final trash requires thirty days and still checks references',async()=>{const f=fixture(),a=await f.manager.acquire(svg),path=a.path;f.manager.records[path].unreferencedSince=Date.now()-GRACE_MS-1;await f.manager.recycle([path]);await assert.rejects(f.manager.trash([path]),/30 天/);f.manager.records[path].recycledAt=Date.now()-31*86400000;f.put('note.md','[['+path+']]');await assert.rejects(f.manager.trash([path]));f.map.delete('note.md');await f.manager.trash([path]);assert.equal(f.manager.records[path],undefined);assert.equal([...f.map.keys()].some(p=>p.endsWith('.svg')),false);});

test('custom folder and friendly naming retain dedup across settings changes and recycle restore',async()=>{const f=fixture();f.plugin.data.assetSettings={folder:'附件/科技树',pattern:'{title}-{seq}'};const a=await f.manager.acquire(svg,'空气压缩机'),path=a.path;assert.match(path,/^附件\/科技树\/空气压缩机-001-[a-f0-9]{12}\.svg$/);f.plugin.data.assetSettings={folder:'另一个位置',pattern:'{date}-{title}'};assert.equal((await f.manager.acquire(svg,'不同标题')).path,path);const b=await f.manager.acquire(svg+'\n','空气压缩机');assert.ok(b.path.startsWith('另一个位置/'));f.manager.records[path].unreferencedSince=Date.now()-GRACE_MS-1;await f.manager.recycle([path]);await f.manager.restore(path);assert.ok(f.map.has(path));assert.equal(f.counts().creates,2);});
test('custom-folder crash recovery verifies marker and hash without adopting unrelated SVGs',async()=>{const f=fixture();f.plugin.data.assetSettings={folder:'附件/卡片'};const a=await f.manager.acquire(svg,'恢复验收'),path=a.path;f.put('附件/卡片/unrelated.svg',svg);f.plugin.data.resources={};await f.manager.observe();assert.equal(Object.keys(f.manager.records).length,1);assert.equal(f.manager.records[path].hash,await sha256(a.text));});
test('reference report lists owning drawings',async()=>{const f=fixture(),a=await f.manager.acquire(svg);f.put('A.excalidraw.md','[['+a.path+']]\n```json\n{"elements":[]}\n```');assert.deepEqual((await f.manager.scan()).rows[0].usedBy,['A.excalidraw.md']);});
