import {test} from 'node:test';import assert from 'node:assert/strict';
import {connectionStyle,DEFAULT_CONNECTION_STYLE,applyConnectionStyle,bindAtSide,arrowEndpoints} from '../src/connection-style.js';
test('default is a rounded elbow and malformed persisted fields are normalized',()=>{assert.equal(connectionStyle().elbowed,true);assert.deepEqual(connectionStyle(null),DEFAULT_CONNECTION_STYLE);assert.equal(connectionStyle({strokeColor:'#12345',strokeWidth:NaN}).strokeColor,'#334155');});
test('capturing a native arrow copies only style, never routes or identities',()=>{const s=connectionStyle({id:'old',elbowed:false,strokeColor:'#2b8a3e',strokeWidth:2,strokeStyle:'dashed',roundness:null,endArrowhead:'triangle',points:[[0,0],[99,99]],startBinding:{elementId:'old-node'},fixedSegments:[{index:1}]});assert.equal(s.elbowed,false);assert.equal(s.strokeColor,'#2b8a3e');for(const k of ['id','points','startBinding','fixedSegments'])assert.equal(k in s,false);});
test('applying style keeps IDs and binding targets but clears incompatible route constraints',()=>{const e={id:'arrow',elbowed:true,x:0,y:0,width:100,height:80,angle:0,points:[[0,0],[40,0],[40,80],[100,80]],fixedSegments:[{index:1}],startBinding:{elementId:'a'},endBinding:{elementId:'b'}};applyConnectionStyle(e,{elbowed:false});assert.equal(e.id,'arrow');assert.equal(e.startBinding.elementId,'a');assert.equal(e.endBinding.elementId,'b');assert.deepEqual(e.points,[[0,0],[100,80]]);assert.equal(e.fixedSegments,null);});
test('same-type style edits retain individually adjusted elbow routes',()=>{const e={elbowed:true,points:[[0,0],[40,0],[40,80],[100,80]],fixedSegments:[{index:2,start:[40,0],end:[40,80]}]};const before=structuredClone(e);applyConnectionStyle(e,{elbowed:true,strokeWidth:3});assert.deepEqual(e.points,before.points);assert.deepEqual(e.fixedSegments,before.fixedSegments);});
test('rotated straight conversion preserves global endpoints and binds at node edges',()=>{const e={elbowed:false,x:105,y:50,width:190,height:0,angle:Math.PI/2,strokeWidth:1,points:[[0,0],[190,0]],startBinding:{elementId:'a'},endBinding:{elementId:'b'}};const before=arrowEndpoints(e);applyConnectionStyle(e,{elbowed:true});const after=arrowEndpoints(e);after.forEach((p,i)=>p.forEach((n,j)=>assert.ok(Math.abs(n-before[i][j])<1e-8)));const node={id:'a',width:100,height:100};bindAtSide(e,'startBinding',node,'right');assert.ok(e.startBinding.fixedPoint[0]>1);assert.equal(e.startBinding.fixedPoint[1],.5);});
test('straight-to-elbow conversion locates the matching endpoint edge',()=>{const a={id:'a',x:0,y:0,width:100,height:100},b={id:'b',x:200,y:100,width:100,height:100};const e={elbowed:false,x:106,y:50,width:88,height:100,angle:0,strokeWidth:2,points:[[0,0],[88,100]],startBinding:{elementId:'a'},endBinding:{elementId:'b'}};applyConnectionStyle(e,{elbowed:true},new Map([['a',a],['b',b]]));assert.ok(e.startBinding.fixedPoint[0]>1);assert.ok(e.endBinding.fixedPoint[0]<0);});
test('negative-direction rotated arrow uses the actual points bounding center',()=>{const e={x:100,y:0,width:100,height:0,angle:Math.PI/2,points:[[0,0],[-100,0]]};const [a,b]=arrowEndpoints(e);assert.ok(Math.abs(a[0]-50)<1e-8&&Math.abs(a[1]-50)<1e-8);assert.ok(Math.abs(b[0]-50)<1e-8&&Math.abs(b[1]+50)<1e-8);});
