import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../src/panel.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export class DetailPanel','globalThis.DetailPanel=class DetailPanel');
const context={Component:class{},console,window:{clearTimeout,setTimeout}};vm.createContext(context);vm.runInContext(source,context);
const el=()=>({hidden:false,classes:new Set(),addClass(c){this.classes.add(c)},removeClass(c){this.classes.delete(c)}});
function fixture(){const p=Object.create(context.DetailPanel.prototype);Object.assign(p,{el:el(),reading:el(),editorHost:el(),modeButton:{disabled:false,textContent:'实时编辑'},preview:{scrollTop:120,scrollLeft:3},editing:false,syncLayout(){},prepareMode:async()=>{}});p.editorHost.hidden=true;p.nativeEditor={editor:{cm:{scrollDOM:{scrollTop:0,scrollLeft:0}},focus(){p.focused=true}}};return p;}
test('reading remains visible while the native editor initializes; repeated toggle is gated',async()=>{const p=fixture();let ready,calls=0;p.prepareMode=()=>{calls++;return new Promise(r=>ready=r)};const pending=p.setMode(true);assert.equal(p.reading.hidden,false);assert.equal(p.editorHost.classes.has('is-preparing'),true);assert.equal(p.modeButton.disabled,true);await p.setMode(true);assert.equal(calls,1);ready();await pending;assert.equal(p.reading.hidden,true);assert.equal(p.editorHost.hidden,false);assert.equal(p.editorHost.classes.has('is-preparing'),false);assert.equal(p.focused,true);assert.equal(p.modeButton.disabled,false);});
test('a failed editor preparation leaves the reading surface usable',async()=>{const p=fixture();p.prepareMode=async()=>{throw Error('unavailable')};await assert.rejects(p.setMode(true),/unavailable/);assert.equal(p.editing,false);assert.equal(p.reading.hidden,false);assert.equal(p.editorHost.hidden,true);assert.equal(p.editorHost.classes.has('is-preparing'),false);assert.equal(p.modeButton.disabled,false);});
test('a failed reading render keeps the existing editor visible',async()=>{const p=fixture();await p.setMode(true);p.prepareMode=async()=>{throw Error('render')};await assert.rejects(p.setMode(false),/render/);assert.equal(p.editing,true);assert.equal(p.reading.hidden,true);assert.equal(p.editorHost.hidden,false);assert.equal(p.modeButton.disabled,false);});
test('each mode retains its own scroll position without mutating the draft',async()=>{const p=fixture();p.draft='原文';await p.setMode(true);p.nativeEditor.editor.cm.scrollDOM.scrollTop=270;await p.setMode(false);assert.equal(p.preview.scrollTop,120);assert.equal(p.preview.scrollLeft,3);p.nativeEditor.editor.cm.scrollDOM.scrollTop=0;await p.setMode(true);assert.equal(p.nativeEditor.editor.cm.scrollDOM.scrollTop,270);assert.equal(p.draft,'原文');});
test('completion from a closed panel cannot reveal or unlock a replacement panel',async()=>{const p=fixture();let ready;p.prepareMode=()=>new Promise(r=>ready=r);const pending=p.setMode(true);p.el=el();p.switching={replacement:true};p.editorHost=el();p.editorHost.hidden=true;p.modeButton={disabled:true};ready();await pending;assert.equal(p.editorHost.hidden,true);assert.equal(p.modeButton.disabled,true);assert.equal(p.switching.replacement,true);assert.equal(p.editing,false);});
test('late native mount is destroyed after the panel has been replaced',async()=>{const p=fixture();p.nativeEditor=null;p.prepareMode=context.DetailPanel.prototype.prepareMode;let ready,disposed=0;context.NativeDetailEditor=class{mount(){return new Promise(r=>ready=r)}destroy(){disposed++}};const pending=p.prepareMode(true);p.el=el();const replacement=p.nativeEditor={replacement:true};ready(true);await pending;assert.equal(disposed,1);assert.equal(p.nativeEditor,replacement);});
