import test from 'node:test';import assert from 'node:assert/strict';
import {editableFields,adjacentField} from '../src/field-navigation.js';
import {radialConfig,radialBinding,bindingMatches,wheelHit,sectorPath} from '../src/radial-model.js';
import {arrowAppState,NativeArrowDefaults} from '../src/native-arrow-defaults.js';
const fields=[{id:'a',type:'title',x:0,y:0,w:100,h:30},{id:'b',type:'field',x:0,y:50,w:100,h:30},{id:'c',type:'summary',x:150,y:0,w:100,h:30}];
test('field arrows follow spatial neighbors and stop at boundary',()=>{assert.equal(adjacentField(fields,'a','ArrowDown'),'b');assert.equal(adjacentField(fields,'a','ArrowRight'),'c');assert.equal(adjacentField(fields,'a','ArrowUp'),'a');assert.deepEqual(editableFields({modules:[...fields,{id:'icon',type:'icon'}]}).map(f=>f.id),['a','c','b']);});
test('single annulus is selectable all around with no seam and retains empty center',()=>{const layout={x:0,y:0,r:120,inner:44};for(let angle=0;angle<Math.PI*2;angle+=.01)assert.equal(wheelHit({x:80*Math.cos(angle),y:80*Math.sin(angle)},layout,1),0);assert.equal(wheelHit({x:0,y:0},layout,1),-1);assert.equal((sectorPath(0,1,120,44).match(/ A /g)||[]).length,4);});
test('multi-sector separator has the same pixel width near inner and outer edges',()=>{for(const radius of [50,100]){assert.equal(wheelHit({x:Math.sqrt(radius*radius-1),y:1},{x:0,y:0,r:120,inner:44},2),-1);assert.equal(wheelHit({x:Math.sqrt(radius*radius-4),y:2},{x:0,y:0,r:120,inner:44},2),1);}});
test('bindings support side buttons and exact modifier matching',()=>{const b=radialBinding({button:4,ctrl:true});assert.equal(bindingMatches({button:4,ctrlKey:true},b),true);assert.equal(bindingMatches({button:4,ctrlKey:true,altKey:true},b),false);const k=radialConfig({trigger:'keyboard',binding:{code:'KeyW',shift:true},delay:2800});assert.equal(k.delay,2800);assert.equal(bindingMatches({code:'KeyW',shiftKey:true},k.binding,true),true);assert.equal(radialBinding({code:'Escape',button:0}).code,'KeyQ');assert.equal(radialBinding({button:0}).button,2);});
function nativeFixture(){let state={activeTool:{type:'selection'},currentItemStrokeColor:'#111111',currentItemStrokeWidthKey:'thin',currentItemRoundness:'round'},patches=[];const p={data:{connectionStyle:{strokeColor:'#00aa00',strokeWidth:3,elbowed:true}}},win={setTimeout:()=>1,clearTimeout(){}},api={getAppState:()=>state,onChange:()=>()=>{},updateScene:patch=>{patches.push(patch);state={...state,...patch.appState};}},v={file:{},excalidrawAPI:api,containerEl:{ownerDocument:{defaultView:win}}},owner={register(){}};const controller=new NativeArrowDefaults(p,v,owner);return {p,v,api,controller,patches,state:()=>state,set:patch=>state={...state,...patch}};}
test('arrow defaults affect only tool state and restore original line defaults on exit',()=>{const f=nativeFixture();f.set({activeTool:{type:'arrow'}});f.controller.sync();assert.equal(f.state().currentItemStrokeColor,'#00aa00');assert.equal(f.state().currentItemArrowType,'elbow');assert.equal(f.state().currentItemStrokeWidth,3);assert.equal(f.patches[0].captureUpdate,'NEVER');assert.equal('elements' in f.patches[0],false);f.set({activeTool:{type:'line'}});f.controller.sync();assert.equal(f.state().currentItemStrokeColor,'#111111');assert.equal(f.state().currentItemStrokeWidthKey,'thin');});
test('native per-session override stays until tool re-entry; drawing in progress is not overwritten',()=>{const f=nativeFixture();f.set({activeTool:{type:'arrow'}});f.controller.sync();f.set({currentItemStrokeColor:'#ee0000'});f.controller.sync();assert.equal(f.state().currentItemStrokeColor,'#ee0000');f.set({newElement:{id:'x'}});f.controller.sync(undefined,true);assert.equal(f.state().currentItemStrokeColor,'#ee0000');f.set({newElement:null});f.controller.sync(undefined,true);assert.equal(f.state().currentItemStrokeColor,'#00aa00');});
test('disabled native synchronization and changed drawing cannot change native defaults',()=>{const f=nativeFixture();f.p.data.nativeArrowDefaults=false;f.set({activeTool:{type:'arrow'}});f.controller.sync();assert.equal(f.patches.length,0);f.p.data.nativeArrowDefaults=true;f.v.file={};f.controller.sync();assert.equal(f.patches.length,0);});
test('native width presets and arbitrary width normalize without leftover key overrides',()=>{assert.equal(arrowAppState({strokeWidth:4}).currentItemStrokeWidthKey,null);assert.equal(arrowAppState({strokeWidth:4}).currentItemStrokeWidth,4);assert.equal(arrowAppState({strokeWidth:1.7}).currentItemStrokeWidth,1.7);});
