import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_TEMPLATE,clone,renderNode,validateTemplate,moduleText} from '../src/model.js';
import {ICONS} from '../src/icons.js';import {modulePreset,placePreset} from '../src/module-presets.js';
const icon=()=>({id:'icon',type:'icon',icon:'atom',label:'原子',x:0,y:0,w:40,h:40,fontSize:14,color:'#1971c2',align:'left'});
test('every built-in icon renders self-contained SVG geometry and no text placeholder',()=>{for(const key of Object.keys(ICONS)){const t={...clone(DEFAULT_TEMPLATE),modules:[{...icon(),icon:key}]};const svg=renderNode(t).svg;assert.ok(svg.includes('viewBox="0 0 24 24"'));assert.ok(!svg.includes('<text'));assert.ok(!svg.includes('href='));assert.ok(!svg.includes('https:'));assert.equal(moduleText(t.modules[0],{}),'');}});
test('unknown icons cannot enter saved templates or inject SVG',()=>{const t={...clone(DEFAULT_TEMPLATE),modules:[{...icon(),icon:'<script>alert(1)</script>'}]};assert.throws(()=>validateTemplate(t),/图标/);});
test('saved module presets are independent copies with user-facing names',()=>{const m=icon(),p=modulePreset(m,'  科技图标  ');m.color='#ffffff';assert.equal(p.name,'科技图标');assert.equal(p.module.color,'#1971c2');assert.throws(()=>modulePreset(m,'  '));});
test('placing presets clips dimensions to small cards, snaps placement and preserves originals',()=>{const t={...clone(DEFAULT_TEMPLATE),width:80,height:64,modules:[]},p=modulePreset({...icon(),w:400,h:100},'大图标'),before=clone(p);const m=placePreset(p,t,90,90);validateTemplate({...t,modules:[m]});assert.deepEqual(p,before);assert.equal(m.w,80);assert.equal(m.h,64);assert.notEqual(m.id,p.module.id);});
test('reusing custom fields creates independent keys instead of mirroring text unexpectedly',()=>{const t=clone(DEFAULT_TEMPLATE),p=modulePreset(t.modules.find(m=>m.type==='field'),'材料行'),m=placePreset(p,t);assert.notEqual(m.field,p.module.field);assert.notEqual(m.id,p.module.id);const clean={...t,modules:[]};assert.equal(placePreset(p,clean).field,p.module.field);});
