import test from 'node:test';
import assert from 'node:assert/strict';
import {fontPlan,rangeMatches,NativeFonts} from '../src/native-fonts.js';
import {fontStack} from '../src/fonts.js';
import {renderNode,DEFAULT_TEMPLATE} from '../src/model.js';
const resource='data:font/woff2;base64,QUJD';
const face=(url,range='U+0000-00FF',weight='400')=>({urls:[url],fontFace:{unicodeRange:range,weight,style:'normal'}});
test('only bundled data font resources enter the SVG, never remote CJK resources',()=>{const registry=new Map([[5,{fontFaces:[face(resource),face('https://example.com/evil.woff2')]}],[100,{fontFaces:[face('https://example.com/cjk.woff2','U+4E00-9FFF')]}]]);const p=fontPlan(registry,'Excalifont','科技 Aa…');assert.equal(p.faces.length,1);assert.ok(p.css.includes(resource));assert.ok(!p.css.includes('http'));assert.ok(p.css.includes('TTNative_Excalifont'));const svg=renderNode(DEFAULT_TEMPLATE,{},undefined,'Excalifont',p.css).svg;assert.ok(svg.includes('<style>@font-face'));assert.ok(svg.includes('TTNative_Excalifont'));});
test('Unicode subsets include astral codepoints, wildcards and locally available CJK',()=>{assert.ok(rangeMatches('U+1F600-1F64F','😀'));assert.ok(rangeMatches('U+4E??','中'));assert.ok(!rangeMatches('U+0041','B'));assert.ok(!rangeMatches('U+0041; color:red','A'));const r=new Map([[5,{fontFaces:[face(resource)]}],[100,{fontFaces:[face(resource,'U+4E00-9FFF')]}]]);assert.equal(fontPlan(r,'Excalifont','中').faces[0].family,'TTNative_Xiaolai');assert.equal(fontPlan(r,'Excalifont','Aa').faces.length,1);});
test('missing native resources are explicit; system fonts stay unchanged',()=>{assert.equal(fontPlan(new Map(),'Virgil','Aa').available,false);assert.equal(fontPlan(new Map(),'Arial','Aa').available,true);assert.equal(fontPlan(new Map(),'Helvetica','Aa').faces.length,0);assert.ok(fontStack('Helvetica').includes('Arial'));assert.ok(fontStack('Microsoft YaHei').startsWith('"Microsoft YaHei"'));assert.equal(fontPlan(new Map([[5,{fontFaces:[face(resource,'U+0041','400;evil')]}]]),'Excalifont','A').css,'');});
test('registration is cached per document and unload removes only owned fonts',async()=>{let count=0;const doc={fonts:new Set(),defaultView:{FontFace:class{constructor(name,src){count++;this.name=name;this.src=src;this.status='unloaded';}async load(){this.status='loaded';return this;}}}},plugin={stopped:false},service=new NativeFonts(plugin),plan=fontPlan(new Map([[5,{fontFaces:[face(resource)]}]]),'Excalifont','Aa');const existing={};doc.fonts.add(existing);await Promise.all([service.ensure(doc,plan),service.ensure(doc,plan)]);assert.equal(count,1);assert.ok(service.ready(doc,plan));service.destroy();assert.deepEqual([...doc.fonts],[existing]);plugin.stopped=true;await assert.rejects(service.ensure(doc,plan),/关闭/);});

test('vertical metrics measure the actual rendered glyphs rather than an unrelated CJK sample',()=>{const measured=[],measure=(text,size)=>text.length*size;measure.metrics=(size,weight,text)=>{measured.push(text);return {ascent:size*.8,descent:size*.2};};renderNode(DEFAULT_TEMPLATE,{title:'气体分离'},measure,'Excalifont');assert.ok(measured.some(t=>t.includes('气体分离')));assert.ok(measured.every(t=>!t.includes('国Ag')));});
