import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {radialConfig,wheelLayout,wheelHit,sectorAngles,sectorPath,moveItem} from '../src/radial-model.js';
const L={x:200,y:200,r:120,inner:44};
test('two actions occupy top and bottom; every count keeps equal distinct centers',()=>{for(let n=1;n<=8;n++)for(let i=0;i<n;i++){const a=sectorAngles(i,n).middle;assert.equal(wheelHit({x:200+82*Math.cos(a),y:200+82*Math.sin(a)},L,n),i);assert.doesNotMatch(sectorPath(i,n,120,44),/NaN|Infinity/);}assert.equal(wheelHit({x:200,y:118},L,2),0);assert.equal(wheelHit({x:200,y:282},L,2),1);});
test('center, outside and sector gaps cancel instead of retaining a selection',()=>{for(const point of [{x:200,y:200},{x:244,y:200},{x:321,y:200},{x:282,y:200}])assert.equal(wheelHit(point,L,2),-1);assert.equal(wheelHit({x:200,y:118},L,0),-1);});
test('clamping preserves invocation point and fits all four canvas corners',()=>{for(const p of [{x:0,y:0},{x:800,y:0},{x:0,y:600},{x:800,y:600}]){const original={...p},layout=wheelLayout(p,{left:0,top:0,right:800,bottom:600},120,44);assert.deepEqual(p,original);assert.ok(layout.x-layout.r>=8&&layout.y-layout.r>=8&&layout.x+layout.r<=792&&layout.y+layout.r<=592);}assert.equal(wheelLayout({x:0,y:0},{left:0,top:0,right:120,bottom:120},120,44),null);});
test('config handles malformed persisted values, caps counts and retains unavailable commands',()=>{assert.equal(radialConfig(null).items.length,4);const c=radialConfig({trigger:'left',delay:1,radius:999,inner:999,items:[null,...Array.from({length:10},()=>({action:'command',command:'missing:command',label:'test',icon:'<script>'}))]});assert.equal(c.trigger,'right');assert.equal(c.delay,100);assert.equal(c.radius,180);assert.equal(c.inner,70);assert.equal(c.items.length,8);assert.equal(c.items[0].command,'missing:command');assert.equal(c.items[0].icon,'terminal');assert.equal(radialConfig({items:[]}).items.length,0);});
test('reorder moves the chosen item without losing or mutating other entries',()=>{const a=['a','b','c'];assert.deepEqual(moveItem(a,0,2),['b','c','a']);assert.deepEqual(a,['a','b','c']);assert.deepEqual(moveItem(a,-1,2),a);});
let source=fs.readFileSync(new URL('../src/radial-menu.js',import.meta.url),'utf8').replace("import {setIcon} from 'obsidian';",'const setIcon=()=>{};').replace("'./radial-model.js'",JSON.stringify(new URL('../src/radial-model.js',import.meta.url).href));
const {RadialMenu}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
function fixture(){const timers=new Map(),listeners=[];let sequence=0;const win={setTimeout:fn=>{timers.set(++sequence,fn);return sequence;},clearTimeout:id=>timers.delete(id)};const doc={defaultView:win};const api={getAppState:()=>({zoom:{value:2},scrollX:10,scrollY:20,offsetLeft:100,offsetTop:50})};const v={file:{path:'test'},excalidrawAPI:api,containerEl:{ownerDocument:doc,contains:()=>true}};const p={data:{radial:radialConfig()},view:()=>v,live:()=>true,selected:()=>null,busy:new Set(),target:()=>({file:v.file,api}),app:{commands:{commands:{}}}};const owner={registerDomEvent:(...args)=>listeners.push(args),register:()=>{}};const r=new RadialMenu(p,v,owner);return {r,p,v,timers,listeners};}
const event=(x=200,y=200)=>({clientX:x,clientY:y,pointerId:1,button:2,target:{tagName:'CANVAS'},altKey:false,ctrlKey:false,shiftKey:false,metaKey:false,preventDefault(){},stopImmediatePropagation(){}});
function open(f){f.r.down(event());const g=f.r.gesture;g.layout=L;g.cells=g.config.items.map(()=>({path:{classList:{toggle(){}}},label:{classList:{toggle(){}}}}));f.r.root={remove(){}};return g;}
test('short click leaves native handling untouched; early movement cancels hold',()=>{const f=fixture();f.r.down(event());assert.ok(f.r.gesture);f.r.up(event());assert.equal(f.r.gesture,null);assert.equal(f.r.consumeUntil,0);f.r.down(event());f.r.move(event(220,200));assert.equal(f.r.gesture,null);assert.equal(f.timers.size,0);});
test('edge relocation without deliberate movement cannot execute',()=>{const f=fixture(),g=open(f);g.layout={...L,x:200,y:282};let called=0;f.r.execute=async()=>called++;f.r.up(event());for(const fn of f.timers.values())fn();assert.equal(called,0);});
test('returning from a highlighted sector to center or outside cancels',()=>{for(const end of [[200,200],[400,200]]){const f=fixture();open(f);f.r.move(event(200,282));assert.equal(f.r.gesture.selected,2);f.r.move(event(...end));assert.equal(f.r.gesture.selected,-1);let calls=0;f.r.execute=()=>calls++;f.r.up(event(...end));for(const fn of f.timers.values())fn();assert.equal(calls,0);}});
test('release rechecks current pointer position and schedules exactly one action',()=>{const f=fixture();open(f);f.r.move(event(200,282));const calls=[];f.r.execute=async(item,g)=>calls.push([item.action,g.scene]);f.r.up(event(200,282));for(const fn of f.timers.values())fn();assert.deepEqual(calls,[['tool:arrow',{x:40,y:55}]]);f.r.up(event(200,282));assert.equal(calls.length,1);});
test('switching view/API or blur cancels pending and active gestures',()=>{const f=fixture();open(f);f.v.excalidrawAPI={};f.r.move(event(200,282));assert.equal(f.r.gesture,null);assert.equal(f.r.root,null);assert.equal(f.r.consumeUntil,Infinity);});
test('disabled command stays in place, does not highlight or execute',()=>{const f=fixture();f.p.data.radial.items[2]={action:'command',command:'missing:command'};open(f);f.r.move(event(200,282));assert.equal(f.r.gesture.selected,-1);f.r.up(event(200,282));assert.equal(f.timers.size,0);});
test('modifier trigger matches exactly and disabled/empty wheel cannot begin',()=>{const f=fixture();f.p.data.radial.trigger='alt-right';f.r.down(event());assert.equal(f.r.gesture,null);f.r.down({...event(),altKey:true});assert.ok(f.r.gesture);f.r.cancel();f.p.data.radial.enabled=false;f.r.down({...event(),altKey:true});assert.equal(f.r.gesture,null);});

test('node actions never follow an unrelated selection changed after opening',async()=>{const f=fixture();let edited=null;f.p.selected=()=>({id:'other'});f.p.openNode=(v,node)=>edited=node;f.p.checkTarget=()=>{};await f.r.execute({action:'edit'},{node:{id:'original'},target:{}});assert.equal(edited,null);await f.r.execute({action:'edit'},{node:null,target:{}});assert.equal(edited,null);f.p.selected=()=>({id:'original'});await f.r.execute({action:'edit'},{node:{id:'original'},target:{}});assert.equal(edited.id,'original');});

test('dedicated command executes own registration and rejects other plugin IDs',async()=>{const f=fixture(),calls=[];f.p.manifest={id:'tech'};f.p.app.commands.commands={'tech:own':{callback(){}},'other:command':{callback(){}}};f.p.app.commands.executeCommandById=id=>calls.push(id);f.p.checkTarget=()=>{};await f.r.execute({action:'plugin-command',command:'tech:own'},{target:{}});await f.r.execute({action:'plugin-command',command:'other:command'},{target:{}});assert.deepEqual(calls,['tech:own']);});
test('dedicated command respects unavailable and removed command conditions',async()=>{const f=fixture(),calls=[];f.p.manifest={id:'tech'};f.p.app.commands.commands={'tech:needs-selection':{checkCallback:()=>false}};f.p.app.commands.executeCommandById=id=>calls.push(id);f.p.checkTarget=()=>{};for(const command of ['tech:needs-selection','tech:missing'])await f.r.execute({action:'plugin-command',command},{target:{}});assert.equal(calls.length,0);});

test('canvas focus transfer does not cancel long press but window blur does',()=>{const f=fixture(),blur=f.listeners.find(([el,type])=>el===f.r.win&&type==='blur')[2];f.r.down(event());blur({target:f.v.containerEl});assert.ok(f.r.gesture);blur({target:f.r.win});assert.equal(f.r.gesture,null);assert.equal(f.timers.size,0);});

test('shape library has one entry but retains all concrete persisted actions',async()=>{const {RADIAL_LIBRARY,RADIAL_ACTIONS,changeRadialAction}=await import('../src/radial-model.js');assert.deepEqual(RADIAL_LIBRARY.filter(([id])=>['tool:rectangle','tool:ellipse','tool:diamond'].includes(id)).map(([id,label])=>[id,label]),[['tool:rectangle','形状']]);assert.ok(RADIAL_ACTIONS.some(([id])=>id==='tool:ellipse'));const item={action:'tool:rectangle',label:'矩形',icon:'square'};changeRadialAction(item,'tool:ellipse');assert.deepEqual(item,{action:'tool:ellipse',label:'椭圆',icon:'circle'});changeRadialAction(item,'tool:diamond');assert.deepEqual(item,{action:'tool:diamond',label:'菱形',icon:'diamond'});item.label='自定义';item.icon='terminal';changeRadialAction(item,'tool:rectangle');assert.equal(item.label,'自定义');assert.equal(item.icon,'terminal');});
