import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {clone,DEFAULT_TEMPLATE,validateTemplate,instance} from '../src/model.js';
const source=fs.readFileSync(new URL('../src/template-view.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export const TEMPLATE_VIEW','const TEMPLATE_VIEW').replace('export class TemplateView','globalThis.TemplateView=class TemplateView').replace('export class ApplyTemplateModal','class ApplyTemplateModal');let n=0;const c={ItemView:class{},Modal:class{},Notice:class{},clone,validateTemplate,uid:()=>`copy-${++n}`};vm.createContext(c);vm.runInContext(source,c);
function fixture(){const a=clone(DEFAULT_TEMPLATE),b={...clone(a),id:'second',name:'第二模板'},views=[],p={data:{templates:[a,b],defaultTemplate:a.id},app:{workspace:{getLeavesOfType:()=>views.map(view=>({view}))}},persist:async()=>{},templates(){return this.data.templates},defaultTemplate(){return this.data.templates.find(t=>t.id===this.data.defaultTemplate)}};const v=Object.create(c.TemplateView.prototype);Object.assign(v,{plugin:p,template:clone(a),dirty:false,build(){}});views.push(v);return {p,v,a,b,views};}
test('template copy has an independent identity and modules, leaving existing card snapshots unchanged',async()=>{const f=fixture(),card=instance(f.a),before=JSON.stringify(card),copy=await f.v.manageTemplate('copy',f.a.id);assert.notEqual(copy.id,f.a.id);assert.equal(copy.version,1);copy.modules[0].x=24;assert.equal(f.a.modules[0].x,16);assert.equal(JSON.stringify(card),before);assert.equal(f.p.data.defaultTemplate,f.a.id);const copy2=await f.v.manageTemplate('copy',f.a.id);assert.notEqual(copy2.name,copy.name);});
test('rename updates saved name and clean editor without rewriting a placed card',async()=>{const f=fixture(),card=instance(f.a);await f.v.manageTemplate('rename',f.a.id,' 新名称 ');assert.equal(f.p.data.templates[0].name,'新名称');assert.equal(f.v.template.name,'新名称');assert.equal(card.template.name,f.a.name);assert.equal(f.p.data.templates[0].version,f.a.version);});
test('deleting the default selects a remaining template and rehomes the clean editor',async()=>{const f=fixture();await f.v.manageTemplate('delete',f.a.id);assert.equal(f.p.data.defaultTemplate,f.b.id);assert.equal(f.v.template.id,f.b.id);assert.equal(f.p.data.templates.length,1);await assert.rejects(f.v.manageTemplate('delete',f.b.id),/至少保留/);});
for(const action of ['rename','delete'])test(action+' protects a live or recovered unsaved draft',async()=>{const f=fixture();f.v.dirty=true;await assert.rejects(f.v.manageTemplate(action,f.a.id,'新名称'),/未保存草稿/);f.v.dirty=false;f.p.data.templateDraft=clone(f.a);await assert.rejects(f.v.manageTemplate(action,f.a.id,'新名称'),/未保存草稿/);assert.equal(f.p.data.templates.length,2);});
for(const action of ['rename','copy','default','delete'])test(action+' restores template collection and default after storage failure',async()=>{const f=fixture(),before=JSON.stringify(f.p.data);f.p.persist=async()=>{throw Error('disk failure')};await assert.rejects(f.v.manageTemplate(action,action==='default'?f.b.id:f.a.id,'新名称'),/disk failure/);assert.equal(JSON.stringify(f.p.data),before);assert.equal(f.p.templateWriteBusy,false);});
test('concurrent template operations are rejected until the first write completes',async()=>{const f=fixture();let resolve;f.p.persist=()=>new Promise(r=>resolve=r);const pending=f.v.manageTemplate('rename',f.a.id,'新名称');await assert.rejects(f.v.manageTemplate('copy',f.b.id),/正在保存/);await assert.rejects(f.v.save(),/正在保存/);resolve();await pending;assert.equal(f.p.templateWriteBusy,false);});
test('failed regular save restores the previous saved template and retained draft',async()=>{const f=fixture();f.v.dirty=true;f.v.template.name='草稿';f.p.data.templateDraft=clone(f.v.template);const before=JSON.stringify(f.p.data);f.p.persist=async()=>{throw Error('disk failure')};await assert.rejects(f.v.save(),/disk failure/);assert.equal(JSON.stringify(f.p.data),before);assert.equal(f.v.dirty,true);});

test('template operations skip deferred workspace views without opening an editor',async()=>{const f=fixture();f.views.push({});await f.v.manageTemplate('rename',f.a.id,'已修改名称');assert.equal(f.p.data.templates[0].name,'已修改名称');await f.v.manageTemplate('delete',f.b.id);assert.equal(f.p.data.templates.length,1);assert.equal(f.views.length,2);});
