import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {clone,DEFAULT_TEMPLATE,validateTemplate} from '../src/model.js';import {resizeTemplate,tidyNumber} from '../src/appearance.js';
const source=fs.readFileSync(new URL('../src/template-view.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export const TEMPLATE_VIEW','const TEMPLATE_VIEW').replace('export class TemplateView','globalThis.TemplateView=class TemplateView').replace('export class ApplyTemplateModal','class ApplyTemplateModal');const c={ItemView:class{},Modal:class{},clone,resizeTemplate,tidyNumber,validateTemplate};vm.createContext(c);vm.runInContext(source,c);
const style=()=>({removeProperty(name){this[name]='';}});
function fixture(){const plugin={data:{},defaultTemplate:()=>DEFAULT_TEMPLATE},v=new c.TemplateView({},plugin),frames=new Map();let next=0;const win={requestAnimationFrame(fn){frames.set(++next,fn);return next;},cancelAnimationFrame(id){frames.delete(id);}};v.contentEl={ownerDocument:{defaultView:win}};v.board={isConnected:true,ownerDocument:{createElement:()=>({})},querySelector:()=>null};v.frames=frames;v.flushFrame=()=>{const jobs=[...frames.values()];frames.clear();jobs.forEach(f=>f());};v.paint=()=>{};v.paintCardResize=()=>{v.partialPaints=(v.partialPaints??0)+1;};v.drawProperties=()=>{};v.changed=()=>{};v.frame={style:style(),getBoundingClientRect:()=>({left:100,top:80}),setPointerCapture(){},hasPointerCapture:()=>false};v.surface={style:style(),getBoundingClientRect:()=>({left:0,top:0,width:900,height:600})};v.cardHandle={focus(){}};return v;}
const start=v=>v.startCardResize({button:0,target:{closest:()=>true},clientX:452,clientY:272,pointerId:1,preventDefault(){},stopPropagation(){}});
test('card resize uses zoom-correct deltas, preserves font size and records one undo step',()=>{const v=fixture(),before=clone(v.template);v.zoom=2;start(v);v.moveCardResize({clientX:580,clientY:336,pointerId:1});v.moveCardResize({clientX:612,clientY:368,pointerId:1});v.endCardResize();assert.equal(v.template.width,432);assert.equal(v.template.height,240);validateTemplate(v.template);assert.deepEqual(v.template.modules,before.modules);assert.equal(v.undoStack.length,1);v.undo();assert.deepEqual(v.template,before);v.redo();assert.equal(v.template.width,432);});
test('card pointer cancellation restores original dimensions without creating history',()=>{const v=fixture(),before=clone(v.template);start(v);v.moveCardResize({clientX:800,clientY:800,pointerId:1});v.endCardResize(true);assert.deepEqual(v.template,before);assert.equal(v.undoStack.length,0);assert.equal(v.frame.style.position,'');});
test('card resize clamps container only and preserves module geometry even beyond edges',()=>{for(const point of [-10000,10000]){const v=fixture();start(v);v.moveCardResize({clientX:point,clientY:point,pointerId:1});v.endCardResize();validateTemplate(v.template,{allowOverflow:true});assert.deepEqual(v.template.modules,DEFAULT_TEMPLATE.modules);assert.ok(v.template.width>=80&&v.template.width<=2400);assert.ok(v.template.height>=64&&v.template.height<=2400);}});
test('a resize burst coalesces to its latest continuous size in one animation frame',()=>{const v=fixture(),modules=clone(v.template.modules);v.zoom=2;start(v);for(let i=1;i<=200;i++)v.moveCardResize({clientX:452+i*.031,clientY:272+i*.017,pointerId:1});assert.equal(v.frames.size,1);assert.equal(v.partialPaints,undefined);assert.equal(v.template.width,352);v.flushFrame();assert.equal(v.partialPaints,1);assert.equal(v.template.width,355.1);assert.equal(v.template.height,193.7);assert.deepEqual(v.template.modules,modules);assert.equal(v.undoStack.length,0);v.endCardResize();assert.equal(v.template.width,352);assert.equal(v.template.height,192);assert.equal(v.undoStack.length,0);});
test('unchanged or foreign-pointer positions do not redraw the resize preview',()=>{const v=fixture();start(v);v.moveCardResize({clientX:500,clientY:500,pointerId:2});assert.equal(v.frames.size,0);v.moveCardResize({clientX:452,clientY:272,pointerId:1});v.flushFrame();assert.equal(v.partialPaints,undefined);v.endCardResize();assert.equal(v.undoStack.length,0);});
test('release commits its final pointer position even before the scheduled frame',()=>{const v=fixture();start(v);v.moveCardResize({clientX:453,clientY:273,pointerId:1});v.endCardResize(false,{clientX:475,clientY:282,pointerId:1});assert.equal(v.frames.size,0);assert.equal(v.template.width,376);assert.equal(v.template.height,200);assert.equal(v.undoStack.length,1);});
test('cancellation prevents late queued callbacks from changing restored or replacement content',()=>{const v=fixture(),before=clone(v.template);start(v);v.moveCardResize({clientX:510,clientY:310,pointerId:1});const late=[...v.frames.values()][0];v.flushFrame();assert.notEqual(v.template.width,before.width);v.moveCardResize({clientX:600,clientY:400,pointerId:1});v.endCardResize(true);assert.equal(v.frames.size,0);assert.deepEqual(v.template,before);const replacement=v.template={...clone(before),width:400};late();assert.equal(v.template,replacement);assert.equal(v.template.width,400);assert.equal(v.undoStack.length,0);});
test('a click without movement preserves dimensions that are not multiples of the grid',()=>{const v=fixture();v.template.width=353;start(v);v.endCardResize(false,{clientX:452,clientY:272,pointerId:1});assert.equal(v.template.width,353);assert.equal(v.undoStack.length,0);});
test('another pointer cannot end an active resize',()=>{const v=fixture();start(v);v.moveCardResize({clientX:500,clientY:300,pointerId:1});v.endCardResize(false,{clientX:700,clientY:600,pointerId:2});assert.ok(v.cardDrag);assert.equal(v.undoStack.length,0);v.endCardResize(true);assert.equal(v.cardDrag,null);});
test('viewport shrink fits the full card and expansion restores preferred zoom',()=>{const v=fixture();v.viewport={isConnected:true,clientWidth:500,clientHeight:350};v.zoomSelect={options:[],createEl:(_,o)=>v.zoomSelect.options.push(o)};v.centerCard=()=>{};v.preferredZoom=1.5;v.adjustViewport();assert.equal(v.zoom,1.28);v.viewport.clientWidth=220;v.viewport.clientHeight=160;v.adjustViewport();assert.ok(v.template.width*v.zoom+48<=220);assert.ok(v.template.height*v.zoom+48<=160);v.viewport.clientWidth=800;v.viewport.clientHeight=700;v.adjustViewport();assert.equal(v.zoom,1.5);});

test('manual zoom is not clamped by a smaller viewport and fit mode restores fitting',()=>{const v=fixture();v.viewport={isConnected:true,clientWidth:220,clientHeight:160};v.zoomSelect={options:[],createEl:(_,o)=>v.zoomSelect.options.push(o)};v.centerCard=()=>{};v.preferredZoom=2;v.zoomMode='manual';v.adjustViewport();assert.equal(v.zoom,2);v.viewport.clientWidth=180;v.adjustViewport();assert.equal(v.zoom,2);v.fitCard();assert.equal(v.zoomMode,'fit');assert.ok(v.zoom*v.template.width+48<=180);});

test('repeated auto-fit keeps fixed presets and only the current transient percentage',()=>{const v=fixture();v.viewport={isConnected:true,clientWidth:500,clientHeight:600};v.centerCard=()=>{};v.zoomSelect={options:[],createEl:(_,o)=>{const option={...o,dataset:o.attr?.['data-dynamic-zoom']?{dynamicZoom:'true'}:{},remove(){v.zoomSelect.options=v.zoomSelect.options.filter(p=>p!==this);}};v.zoomSelect.options.push(option);return option;}};for(const n of [.5,.75,1,1.25,1.5,2])v.zoomSelect.createEl('option',{value:String(n)});for(let i=0;i<120;i++){v.viewport.clientWidth=220+(i*17)%600;v.adjustViewport();assert.ok(v.zoomSelect.options.length<=7);assert.ok(v.zoomSelect.options.some(o=>Number(o.value)===v.zoom));}v.zoomMode='manual';v.preferredZoom=1;v.adjustViewport();assert.equal(v.zoomSelect.options.length,6);assert.equal(v.zoom,1);});

test('returning to an existing drawing reveals then explicitly activates and focuses it',async()=>{const v=fixture(),calls=[],leaf={view:{file:{path:'drawing'},containerEl:{ownerDocument:{defaultView:{focus:()=>calls.push('window')}},querySelector:()=>({focus:()=>calls.push('canvas')})}}};v.plugin.origin={leaf,path:'drawing'};v.app={workspace:{revealLeaf:async l=>{assert.equal(l,leaf);calls.push('reveal');},setActiveLeaf:(l,options)=>{assert.equal(l,leaf);assert.equal(options.focus,true);calls.push('active');}}};await v.returnToTree();assert.deepEqual(calls,['reveal','active','window','canvas']);});
test('returning after the original leaf closes opens and activates the original file',async()=>{const v=fixture(),calls=[],file={path:'drawing'},leaf={view:{},openFile:async f=>{assert.equal(f,file);calls.push('open');}};v.plugin.origin={leaf:{view:{}},path:'drawing'};v.app={vault:{getAbstractFileByPath:()=>file},workspace:{getLeaf:()=>leaf,revealLeaf:async()=>calls.push('reveal'),setActiveLeaf:l=>{assert.equal(l,leaf);calls.push('active');}}};await v.returnToTree();assert.deepEqual(calls,['open','reveal','active']);});
