import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {NativeFonts} from '../src/native-fonts.js';import {NATIVE_FONTS} from '../src/fonts.js';import {DEFAULT_TEMPLATE,clone,validateTemplate,renderNode,outsideModules,instance} from '../src/model.js';import {resizeTemplate} from '../src/appearance.js';
import {dependencyState,EXCALIDRAW_ID} from '../src/dependency.js';
const full=()=>new Map(NATIVE_FONTS.map(f=>[f.id,{fontFaces:[{urls:['data:font/woff2;base64,QUJD'],fontFace:{weight:'400',style:'normal',unicodeRange:'U+0-10FFFF'}}]}]));
function fontFixture(){const timers=new Map();let id=0;const win={setTimeout:f=>{timers.set(++id,f);return id;},clearTimeout:i=>timers.delete(i)},doc={defaultView:win},plugin={app:{plugins:{plugins:{}}}},service=new NativeFonts(plugin);return {timers,win,doc,plugin,service,tick(){const entry=timers.entries().next().value;assert.ok(entry);timers.delete(entry[0]);entry[1]();},ready(){plugin.app.plugins.plugins['obsidian-excalidraw-plugin']={packageManager:{packageMap:new Map([[win,{excalidrawLib:{Fonts:{registered:full()}}}]])}};}};}
test('font list observes delayed dependency readiness and stops when complete',()=>{const f=fontFixture(),events=[];f.service.watch(f.doc,(names,state)=>events.push({names,state}));assert.equal(events[0].state,'waiting');assert.deepEqual(events[0].names,['Helvetica']);f.ready();f.tick();assert.equal(events.at(-1).state,'ready');assert.equal(events.at(-1).names.length,7);assert.equal(f.timers.size,0);assert.equal(f.service.watchers.size,0);});
test('font readiness timeout is bounded and manual cancellation removes timers',()=>{const f=fontFixture(),events=[];f.service.watch(f.doc,(_,state)=>events.push(state));for(let i=0;i<150;i++)f.tick();assert.equal(events.at(-1),'unavailable');assert.equal(f.timers.size,0);const stop=f.service.watch(f.doc,()=>{});stop();assert.equal(f.timers.size,0);f.service.watch(f.doc,()=>{});f.service.destroy();assert.equal(f.timers.size,0);});
test('an empty secondary window registry cannot hide available bundled fonts',()=>{const f=fontFixture();f.ready();const pm=f.plugin.app.plugins.plugins['obsidian-excalidraw-plugin'].packageManager;pm.packageMap.set({},pm.packageMap.get(f.win));pm.packageMap.set(f.win,{excalidrawLib:{Fonts:{registered:new Map()}}});assert.equal(f.service.names(f.doc).length,7);});
const source=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export default class TechTreePlugin','globalThis.TechTreePlugin=class TechTreePlugin');
function scanFixture(){const timers=new Map(),listeners=[],ctx={Plugin:class{},dependencyState,Date:{now:()=>0},setTimeout:f=>{timers.set(1,f);return 1;},clearTimeout:i=>timers.delete(i)};ctx.window={setTimeout:ctx.setTimeout,clearTimeout:ctx.clearTimeout};vm.createContext(ctx);vm.runInContext(source,ctx);const p=new ctx.TechTreePlugin(),doc={},v={file:{path:'drawing'},_loaded:false,containerEl:{ownerDocument:doc,contains:()=>true},removeChild:o=>{p.removed=(p.removed??0)+1;}},leaf={view:v};v.leaf=leaf;Object.assign(p,{owners:new Map(),canvasDocuments:new Set(),scanUntil:30000,app:{plugins:{plugins:{[EXCALIDRAW_ID]:{manifest:{version:'2.28.0'},isExcalidrawFile:()=>false}}},workspace:{getLeavesOfType:()=>[leaf]}},registerDomEvent:(d,type,fn)=>listeners.push(fn),attach(view){p.owners.set(view,{file:view.file,api:view.excalidrawAPI,radial:{down:()=>p.forwarded=(p.forwarded??0)+1}});p.attached=(p.attached??0)+1;}});return {p,v,leaf,timers,listeners,tick(){const f=timers.get(1);timers.delete(1);f();}};}
test('delayed drawing API gets attached without an additional layout event',()=>{const f=scanFixture();f.p.scheduleScan();assert.equal(f.p.owners.size,0);f.v._loaded=true;f.v.excalidrawAPI={};f.tick();assert.equal(f.p.attached,1);assert.equal(f.timers.size,0);f.p.scan();assert.equal(f.p.attached,1);});
test('first canvas pointer fills the readiness gap and forwards the same gesture once',()=>{const f=scanFixture();f.p.scheduleScan();f.v._loaded=true;f.v.excalidrawAPI={};f.listeners[0]({target:{tagName:'CANVAS'}});assert.equal(f.p.attached,1);assert.equal(f.p.forwarded,1);f.listeners[0]({target:{tagName:'CANVAS'}});assert.equal(f.p.forwarded,1);});
test('API replacement reattaches once and a closed view releases its owner',()=>{const f=scanFixture();f.v._loaded=true;f.v.excalidrawAPI={};f.p.scheduleScan();f.v.excalidrawAPI={};f.p.scan();assert.equal(f.p.attached,2);assert.equal(f.p.removed,1);f.p.app.workspace.getLeavesOfType=()=>[];f.p.scan();assert.equal(f.p.owners.size,0);assert.equal(f.p.removed,2);});
test('readiness polling stops at its deadline and unload blocks later attachment',()=>{const f=scanFixture();f.p.scanUntil=-1;f.p.scan();assert.equal(f.timers.size,0);f.p.scheduleScan();f.p.stopped=true;f.v._loaded=true;f.v.excalidrawAPI={};f.tick();assert.equal(f.p.owners.size,0);});
test('container shrink preserves modules, remains previewable, and cannot be committed out of bounds',()=>{const t=clone(DEFAULT_TEMPLATE),before=clone(t.modules);resizeTemplate(t,100,80);assert.deepEqual(t.modules,before);assert.ok(outsideModules(t).length);assert.doesNotThrow(()=>renderNode(t,{},undefined,undefined,'',{allowOverflow:true}));assert.throws(()=>instance(t),/边界/);resizeTemplate(t,352,192);assert.equal(outsideModules(t).length,0);validateTemplate(t);assert.deepEqual(t.modules,before);});
