import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {FONT_SIZES,moduleDefaultFontSize,DEFAULT_TEMPLATE,clone,renderNode,validateTemplate} from '../src/model.js';import {modulePreset,placePreset} from '../src/module-presets.js';
let source=fs.readFileSync(new URL('../src/wheel-editor-motion.js',import.meta.url),'utf8').replace("import {setIcon} from 'obsidian';",'const setIcon=()=>{};').replace("'./radial-model.js'",JSON.stringify(new URL('../src/radial-model.js',import.meta.url).href));const {previewItems,dropIndex,WheelDrag}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
test('default template and every newly created text module use basic size presets',()=>{for(const m of DEFAULT_TEMPLATE.modules)assert.ok(FONT_SIZES.includes(m.fontSize));for(const type of ['title','summary','field','text','button'])assert.ok(FONT_SIZES.includes(moduleDefaultFontSize(type)));});
test('button solid fill is independent of text and falls back for old templates',()=>{const t=clone(DEFAULT_TEMPLATE),button=t.modules.find(m=>m.type==='button');assert.ok(renderNode(t).svg.includes('fill="#dbeafe"'));button.fillColor='#ffcc33';const svg=renderNode(t).svg;assert.ok(svg.includes('fill="#ffcc33"'));assert.ok(svg.includes(`stroke="${button.color}"`));const preset=modulePreset(button,'彩色按钮'),placed=placePreset(preset,t);assert.equal(placed.fillColor,'#ffcc33');assert.equal(JSON.parse(JSON.stringify(t)).modules.at(-1).fillColor,'#ffcc33');});
test('button fill rejects invalid SVG and retains legacy absence',()=>{const t=clone(DEFAULT_TEMPLATE),b=t.modules.at(-1);validateTemplate(t);for(const v of ['transparent','red','"/><script>',null,42]){b.fillColor=v;assert.throws(()=>validateTemplate(t),/填充/);}});
test('drag preview adds or moves without changing committed items until release',()=>{const items=[{id:'a'},{id:'b'},{id:'c'}],before=JSON.stringify(items),item={id:'new'};assert.deepEqual(previewItems(items,{item},1).map(i=>i.id),['a','new','b','c']);assert.deepEqual(previewItems(items,{index:0,item:items[0]},2).map(i=>i.id),['b','c','a']);assert.equal(JSON.stringify(items),before);assert.equal(previewItems(items,{item},-1),items);});
test('removal is explicit and full wheel refuses insertion',()=>{const items=Array.from({length:8},(_,i)=>({id:String(i)}));assert.equal(previewItems(items,{item:{id:'new'}},1),items);assert.equal(previewItems(items,{index:2,item:items[2]},-1,true).length,7);assert.equal(previewItems(items,{item:{id:'new'}},-1,true),items);});
test('drop targeting supports empty ring, cancel center and stable angular slots',()=>{assert.equal(dropIndex(170,170,0),0);assert.equal(dropIndex(170,170,4),-1);assert.equal(dropIndex(600,600,4),-1);assert.equal(dropIndex(170,50,4),0);assert.equal(dropIndex(290,170,4),1);});

test('configurable neutral center rejects drop until pointer leaves actual inner radius',()=>{assert.equal(dropIndex(170,90,4,94),-1);assert.equal(dropIndex(170,60,4,94),0);});
test('focus moving between editor controls never cancels a drag; actual window blur does',()=>{const target=()=>({events:{},addEventListener(t,f){this.events[t]=f;},removeEventListener(t){delete this.events[t];}}),win=target(),doc={...target(),defaultView:win},contentEl={...target(),ownerDocument:doc},d=new WheelDrag({contentEl});let cancelled=0;d.cancel=()=>cancelled++;win.events.blur({target:contentEl});assert.equal(cancelled,0);win.events.blur({target:win});assert.equal(cancelled,1);d.destroy();assert.equal(Object.keys(win.events).length,0);assert.equal(Object.keys(doc.events).length,0);});

test('return animation preserves screen coordinates when shrinking and cleans up',()=>{let frames,options,animation={},removed=0;const ghost={animate(f,o){frames=f;options=o;return animation;},remove(){removed++;}},d=Object.create(WheelDrag.prototype);d.win={matchMedia:()=>({matches:false})};d.effects=new Set();d.finishOrb(ghost,{x:400,y:300},{x:80,y:120});assert.equal(frames[0].transform,'translate3d(378px,278px,0) scale(1)');assert.equal(frames[1].transform,'translate3d(58px,98px,0) scale(0.25)');assert.equal(options.duration,220);assert.equal(d.effects.size,1);animation.onfinish();assert.equal(removed,1);assert.equal(d.effects.size,0);});
test('reduced motion removes the orb without a return flight',()=>{let removed=0;const d=Object.create(WheelDrag.prototype);d.win={matchMedia:()=>({matches:true})};d.finishOrb({remove(){removed++;},animate(){throw Error('unexpected animation');}},{x:1,y:2},{x:3,y:4});assert.equal(removed,1);});
